<?php

class object_html_color_codes extends object_data {
	public $column_key = 'code';
	public $column_prefix = 'no_html_color_code_';
	public $columns = [
		'code' => ['name' => 'Group Code', 'type' => 'char', 'length' => 6],
		'name' => ['name' => 'Name', 'type' => 'text'],
		'html_name' => ['name' => 'HTML Name', 'type' => 'text'],
		'group' => ['name' => 'Color Group', 'domain' => 'html_color_group']
	];
	public $optgroups_map = [
		'column' => 'no_html_color_code_group',
		'model' => 'object_html_color_groups'
	];
	public $data = [
		// Basic
		'FFFFFF' => ['name' => 'White', 'html_name' => 'white', 'group' => 'basic'],
		'808080' => ['name' => 'Gray', 'html_name' => 'gray', 'group' => 'basic'],
		'C0C0C0' => ['name' => 'Silver', 'html_name' => 'silver', 'group' => 'basic'],
		'000000' => ['name' => 'Black', 'html_name' => 'black', 'group' => 'basic'],
		'800000' => ['name' => 'Maroon', 'html_name' => 'maroon', 'group' => 'basic'],
		'FF0000' => ['name' => 'Red', 'html_name' => 'red', 'group' => 'basic'],
		'800080' => ['name' => 'Purple', 'html_name' => 'purple', 'group' => 'basic'],
		'FF00FF' => ['name' => 'Fuchsia', 'html_name' => 'fuchsia', 'group' => 'basic'],
		'008000' => ['name' => 'Green', 'html_name' => 'green', 'group' => 'basic'],
		'00FF00' => ['name' => 'Lime', 'html_name' => 'lime', 'group' => 'basic'],
		'808000' => ['name' => 'Olive', 'html_name' => 'olive', 'group' => 'basic'],
		'FFFF00' => ['name' => 'Yellow', 'html_name' => 'yellow', 'group' => 'basic'],
		'000080' => ['name' => 'Navy', 'html_name' => 'navy', 'group' => 'basic'],
		'0000FF' => ['name' => 'Blue', 'html_name' => 'blue', 'group' => 'basic'],
		'008080' => ['name' => 'Teal', 'html_name' => 'teal', 'group' => 'basic'],
		'00FFFF' => ['name' => 'Aqua', 'html_name' => 'aqua', 'group' => 'basic'],
		'FFA500' => ['name' => 'Orange', 'html_name' => 'orange', 'group' => 'basic'],
		// Red(s)
		'CD5C5C' => ['name' => 'Indian Red', 'html_name' => 'indianred', 'group' => 'reds'],
		'F08080' => ['name' => 'Light Coral', 'html_name' => 'lightcoral', 'group' => 'reds'],
		'FA8072' => ['name' => 'Salmon', 'html_name' => 'salmon', 'group' => 'reds'],
		'E9967A' => ['name' => 'Dark Salmon', 'html_name' => 'darksalmon', 'group' => 'reds'],
		'FFA07A' => ['name' => 'Light Salmon', 'html_name' => 'lightsalmon', 'group' => 'reds'],
		'DC143C' => ['name' => 'Crimson', 'html_name' => 'crimson', 'group' => 'reds'],
		'B22222' => ['name' => 'Firebrick', 'html_name' => 'firebrick', 'group' => 'reds'],
		'8B0000' => ['name' => 'Dark Red', 'html_name' => 'darkred', 'group' => 'reds'],
		// Pink(s)
		'FFC0CB' => ['name' => 'Pink', 'html_name' => 'pink', 'group' => 'pinks'],
		'FFB6C1' => ['name' => 'Light Pink', 'html_name' => 'lightpink', 'group' => 'pinks'],
		'FF69B4' => ['name' => 'Hot Pink', 'html_name' => 'hotpink', 'group' => 'pinks'],
		'FF1493' => ['name' => 'Deep Pink', 'html_name' => 'deeppink', 'group' => 'pinks'],
		'C71585' => ['name' => 'Medium Violet Red', 'html_name' => 'mediumvioletred', 'group' => 'pinks'],
		'DB7093' => ['name' => 'Pale Violet Red', 'html_name' => 'palevioletred', 'group' => 'pinks'],
		// Orange(s)
		'FFA07A' => ['name' => 'Light Salmon', 'html_name' => 'lightsalmon', 'group' => 'oranges'],
		'FF7F50' => ['name' => 'Coral', 'html_name' => 'coral', 'group' => 'oranges'],
		'FF6347' => ['name' => 'Tomato', 'html_name' => 'tomato', 'group' => 'oranges'],
		'FF4500' => ['name' => 'Orange Red', 'html_name' => 'orangered', 'group' => 'oranges'],
		'FF8C00' => ['name' => 'Dark Orange', 'html_name' => 'darkorange', 'group' => 'oranges'],
		// Yellow(s)
		'FFD700' => ['name' => 'Gold', 'html_name' => 'gold', 'group' => 'yellows'],
		'FFFFE0' => ['name' => 'Light Yellow', 'html_name' => 'lightyellow', 'group' => 'yellows'],
		'FFFACD' => ['name' => 'Lemon Chiffon', 'html_name' => 'lemonchiffon', 'group' => 'yellows'],
		'FAFAD2' => ['name' => 'Light Goldenrod Yellow', 'html_name' => 'lightgoldenrodyellow', 'group' => 'yellows'],
		'FFEFD5' => ['name' => 'Papaya Whip', 'html_name' => 'papayawhip', 'group' => 'yellows'],
		'FFE4B5' => ['name' => 'Moccasin', 'html_name' => 'moccasin', 'group' => 'yellows'],
		'FFDAB9' => ['name' => 'Peach Puff', 'html_name' => 'peachpuff', 'group' => 'yellows'],
		'EEE8AA' => ['name' => 'Pale Goldenrod', 'html_name' => 'palegoldenrod', 'group' => 'yellows'],
		'F0E68C' => ['name' => 'Khaki', 'html_name' => 'khaki', 'group' => 'yellows'],
		'BDB76B' => ['name' => 'Dark Khaki', 'html_name' => 'darkkhaki', 'group' => 'yellows'],
		// Purple(s)
		'E6E6FA' => ['name' => 'Lavender', 'html_name' => 'lavender', 'group' => 'purples'],
		'D8BFD8' => ['name' => 'Thistle', 'html_name' => 'thistle', 'group' => 'purples'],
		'DDA0DD' => ['name' => 'Plum', 'html_name' => 'plum', 'group' => 'purples'],
		'EE82EE' => ['name' => 'Violet', 'html_name' => 'violet', 'group' => 'purples'],
		'DA70D6' => ['name' => 'Orchid', 'html_name' => 'orchid', 'group' => 'purples'],
		'BA55D3' => ['name' => 'Medium Orchid', 'html_name' => 'mediumorchid', 'group' => 'purples'],
		'9370DB' => ['name' => 'Medium Purple', 'html_name' => 'mediumpurple', 'group' => 'purples'],
		'8A2BE2' => ['name' => 'Blue Violet', 'html_name' => 'blueviolet', 'group' => 'purples'],
		'9400D3' => ['name' => 'Dark Violet', 'html_name' => 'darkviolet', 'group' => 'purples'],
		'9932CC' => ['name' => 'Dark Orchid', 'html_name' => 'darkorchid', 'group' => 'purples'],
		'8B008B' => ['name' => 'Dark Magenta', 'html_name' => 'darkmagenta', 'group' => 'purples'],
		'4B0082' => ['name' => 'Indigo', 'html_name' => 'indigo', 'group' => 'purples'],
		'6A5ACD' => ['name' => 'Slate Blue', 'html_name' => 'slateblue', 'group' => 'purples'],
		'483D8B' => ['name' => 'Dark Slate Blue', 'html_name' => 'darkslateblue', 'group' => 'purples'],
		'7B68EE' => ['name' => 'Medium Slate Blue', 'html_name' => 'mediumslateblue', 'group' => 'purples'],
		// Green(s)
		'ADFF2F' => ['name' => 'Green Yellow', 'html_name' => 'greenyellow', 'group' => 'greens'],
		'7FFF00' => ['name' => 'Chartreuse', 'html_name' => 'chartreuse', 'group' => 'greens'],
		'7CFC00' => ['name' => 'Lawn Green', 'html_name' => 'lawngreen', 'group' => 'greens'],
		'32CD32' => ['name' => 'Lime Green', 'html_name' => 'limegreen', 'group' => 'greens'],
		'98FB98' => ['name' => 'Pale Green', 'html_name' => 'palegreen', 'group' => 'greens'],
		'90EE90' => ['name' => 'Light Green', 'html_name' => 'lightgreen', 'group' => 'greens'],
		'00FA9A' => ['name' => 'Medium Spring Green', 'html_name' => 'mediumspringgreen', 'group' => 'greens'],
		'00FF7F' => ['name' => 'Spring Green', 'html_name' => 'springgreen', 'group' => 'greens'],
		'3CB371' => ['name' => 'Medium Sea Green', 'html_name' => 'mediumseagreen', 'group' => 'greens'],
		'2E8B57' => ['name' => 'Sea Green', 'html_name' => 'seagreen', 'group' => 'greens'],
		'228B22' => ['name' => 'Forest Green', 'html_name' => 'forestgreen', 'group' => 'greens'],
		'006400' => ['name' => 'Dark Green', 'html_name' => 'darkgreen', 'group' => 'greens'],
		'9ACD32' => ['name' => 'Yellow Green', 'html_name' => 'yellowgreen', 'group' => 'greens'],
		'6B8E23' => ['name' => 'Olive Drab', 'html_name' => 'olivedrab', 'group' => 'greens'],
		'556B2F' => ['name' => 'Dark Olive Green', 'html_name' => 'darkolivegreen', 'group' => 'greens'],
		'66CDAA' => ['name' => 'Medium Aquamarine', 'html_name' => 'mediumaquamarine', 'group' => 'greens'],
		'8FBC8F' => ['name' => 'Dark Sea Green', 'html_name' => 'darkseagreen', 'group' => 'greens'],
		'20B2AA' => ['name' => 'Light Sea Green', 'html_name' => 'lightseagreen', 'group' => 'greens'],
		'008B8B' => ['name' => 'Dark Cyan', 'html_name' => 'darkcyan', 'group' => 'greens'],
		// Blue(s) 
	    	'E0FFFF' => ['name' => 'Light Cyan', 'html_name' => 'lightcyan', 'group' => 'blues'],
		'AFEEEE' => ['name' => 'Pale Turquoise', 'html_name' => 'paleturquoise', 'group' => 'blues'],
		'7FFFD4' => ['name' => 'Aquamarine', 'html_name' => 'aquamarine', 'group' => 'blues'],
		'40E0D0' => ['name' => 'Turquoise', 'html_name' => 'turquoise', 'group' => 'blues'],
		'48D1CC' => ['name' => 'Medium Turquoise', 'html_name' => 'mediumturquoise', 'group' => 'blues'],
		'00CED1' => ['name' => 'Dark Turquoise', 'html_name' => 'darkturquoise', 'group' => 'blues'],
		'5F9EA0' => ['name' => 'Cadet Blue', 'html_name' => 'cadetblue', 'group' => 'blues'],
		'4682B4' => ['name' => 'Steel Blue', 'html_name' => 'steelblue', 'group' => 'blues'],
		'B0C4DE' => ['name' => 'Light Steel Blue', 'html_name' => 'lightsteelblue', 'group' => 'blues'],
		'B0E0E6' => ['name' => 'Powder Blue', 'html_name' => 'powderblue', 'group' => 'blues'],
		'ADD8E6' => ['name' => 'Light Blue', 'html_name' => 'lightblue', 'group' => 'blues'],
		'87CEEB' => ['name' => 'Sky Blue', 'html_name' => 'skyblue', 'group' => 'blues'],
		'87CEFA' => ['name' => 'Light Sky Blue', 'html_name' => 'lightskyblue', 'group' => 'blues'],
		'00BFFF' => ['name' => 'Deep Sky Blue', 'html_name' => 'deepskyblue', 'group' => 'blues'],
		'1E90FF' => ['name' => 'Dodger Blue', 'html_name' => 'dodgerblue', 'group' => 'blues'],
		'6495ED' => ['name' => 'Cornflower Blue', 'html_name' => 'cornflowerblue', 'group' => 'blues'],
		'7B68EE' => ['name' => 'Medium Slate Blue', 'html_name' => 'mediumslateblue', 'group' => 'blues'],
		'4169E1' => ['name' => 'Royal Blue', 'html_name' => 'royalblue', 'group' => 'blues'],
		'0000CD' => ['name' => 'Medium Blue', 'html_name' => 'mediumblue', 'group' => 'blues'],
		'00008B' => ['name' => 'Dark Blue', 'html_name' => 'darkblue', 'group' => 'blues'],
		'191970' => ['name' => 'Midnight Blue', 'html_name' => 'midnightblue', 'group' => 'blues'],
		// Brown(s)
	    	'FFF8DC' => ['name' => 'Cornsilk', 'html_name' => 'cornsilk', 'group' => 'browns'],
		'FFEBCD' => ['name' => 'Blanched Almond', 'html_name' => 'blanchedalmond', 'group' => 'browns'],
		'FFE4C4' => ['name' => 'Bisque', 'html_name' => 'bisque', 'group' => 'browns'],
		'FFDEAD' => ['name' => 'Navajo White', 'html_name' => 'navajowhite', 'group' => 'browns'],
		'F5DEB3' => ['name' => 'Wheat', 'html_name' => 'wheat', 'group' => 'browns'],
		'DEB887' => ['name' => 'Burlywood', 'html_name' => 'burlywood', 'group' => 'browns'],
		'D2B48C' => ['name' => 'Tan', 'html_name' => 'tan', 'group' => 'browns'],
		'BC8F8F' => ['name' => 'Rosy Brown', 'html_name' => 'rosybrown', 'group' => 'browns'],
		'F4A460' => ['name' => 'Sandy Brown', 'html_name' => 'sandybrown', 'group' => 'browns'],
		'DAA520' => ['name' => 'Goldenrod', 'html_name' => 'goldenrod', 'group' => 'browns'],
		'B8860B' => ['name' => 'Dark Goldenrod', 'html_name' => 'darkgoldenrod', 'group' => 'browns'],
		'CD853F' => ['name' => 'Peru', 'html_name' => 'peru', 'group' => 'browns'],
		'D2691E' => ['name' => 'Chocolate', 'html_name' => 'chocolate', 'group' => 'browns'],
		'8B4513' => ['name' => 'Saddle Brown', 'html_name' => 'saddlebrown', 'group' => 'browns'],
		'A0522D' => ['name' => 'Sienna', 'html_name' => 'sienna', 'group' => 'browns'],
		'A52A2A' => ['name' => 'Brown', 'html_name' => 'brown', 'group' => 'browns'],
		// White(s)
	        'FFFAFA' => ['name' => 'Snow', 'html_name' => 'snow', 'group' => 'whites'],
		'F0FFF0' => ['name' => 'Honeydew', 'html_name' => 'honeydew', 'group' => 'whites'],
		'F5FFFA' => ['name' => 'Mint Cream', 'html_name' => 'mintcream', 'group' => 'whites'],
		'F0FFFF' => ['name' => 'Azure', 'html_name' => 'azure', 'group' => 'whites'],
		'F0F8FF' => ['name' => 'Alice Blue', 'html_name' => 'aliceblue', 'group' => 'whites'],
		'F8F8FF' => ['name' => 'Ghost White', 'html_name' => 'ghostwhite', 'group' => 'whites'],
		'F5F5F5' => ['name' => 'White Smoke', 'html_name' => 'whitesmoke', 'group' => 'whites'],
		'FFF5EE' => ['name' => 'Seashell', 'html_name' => 'seashell', 'group' => 'whites'],
		'F5F5DC' => ['name' => 'Beige', 'html_name' => 'beige', 'group' => 'whites'],
		'FDF5E6' => ['name' => 'Old Lace', 'html_name' => 'oldlace', 'group' => 'whites'],
		'FFFAF0' => ['name' => 'Floral White', 'html_name' => 'floralwhite', 'group' => 'whites'],
		'FFFFF0' => ['name' => 'Ivory', 'html_name' => 'ivory', 'group' => 'whites'],
		'FAEBD7' => ['name' => 'Antique White', 'html_name' => 'antiquewhite', 'group' => 'whites'],
		'FAF0E6' => ['name' => 'Linen', 'html_name' => 'linen', 'group' => 'whites'],
		'FFF0F5' => ['name' => 'Lavender Blush', 'html_name' => 'lavenderblush', 'group' => 'whites'],
		'FFE4E1' => ['name' => 'Misty Rose', 'html_name' => 'mistyrose', 'group' => 'whites'],
		// Gray(s)
		'DCDCDC' => ['name' => 'Gainsboro', 'html_name' => 'gainsboro', 'group' => 'grays'],
		'D3D3D3' => ['name' => 'Light Gray', 'html_name' => 'lightgray', 'group' => 'grays'],
		'A9A9A9' => ['name' => 'Dark Gray', 'html_name' => 'darkgray', 'group' => 'grays'],
		'696969' => ['name' => 'Dim Gray', 'html_name' => 'dimgray', 'group' => 'grays'],
		'778899' => ['name' => 'Light Slate Gray', 'html_name' => 'lightslategray', 'group' => 'grays'],
		'708090' => ['name' => 'Slate Gray', 'html_name' => 'slategray', 'group' => 'grays'],
		'2F4F4F' => ['name' => 'Dark Slate Gray', 'html_name' => 'darkslategray', 'group' => 'grays']
	];
}
